export EDITOR="micro" # pkgx
export HOMEBREW_NO_ANALYTICS=1
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export VIRTUAL_ENV_DISABLE_PROMPT=1 # stop issue where virtualenv was erroneously appearing at the end of every cmd output
export PATH=$PATH:$HOME/.local/bin/go # pkgx
export GOPATH=$HOME/go
export PATH=$PATH:$HOME/go/bin/
export MICRO_TRUECOLOR=1
export VAULT_ADDR="https://vault.local.timmybtech.com"
export KUBECONFIG="/home/timmyb824/.kube/config_k3s"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/.basher/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion) # prevents an issue with autosuggestions and atuin where terminal line moves off screen
